---
abstract: 'Compare version strings'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Version-Compare
requires:
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gittex/Version-Compare/issues
  repository: git://github.com/gittex/Version-Compare.git
version: 0.15.0
x_authority: cpan:TEX
